### ISSUE TITLE
briekit-event-filter

### ISSUE THREAD

**Issue by Ivymanman** [huangyh09/briekit#1]
hi,I got this error when I run 
briekit-event-filter -a /path/to/A3SS.gff3.gz --anno_ref /path/to/gencode.vM22.annotation.gff3 -r /path/to/GRCm38.p6.genome.fa

5955 Skipped Exon events are input for quality check.
0 Skipped Exon events pass the qulity control.
Traceback (most recent call last):
  File "xxxx/envs/briekit/bin/briekit-event-filter", line 10, in <module>
    sys.exit(main())
  File "xxxx/miniconda2/envs/briekit/lib/python2.7/site-packages/briekit/events/event_filter.py", line 395, in main
    g_idx, g_chr, g_start, g_stop = get_gene_idx(anno_out)
  File "xxx/miniconda2/envs/briekit/lib/python2.7/site-packages/briekit/events/event_filter.py", line 41, in get_gene_idx
    g_idx.append([now_g, last_g])
UnboundLocalError: local variable 'last_g' referenced before assignment

**Comment by huangyh09** [comment]
Hi, the briekit-event-filter is only for the skipping exon events. You may need to define your own filters for the A3SS (alternative 3' splice site) event, which we haven't looked into.

**Comment by Ivymanman** [comment]
Thanks a lot 😅发自我的iPhone------------------ Original ------------------From: Yuanhua Huang  <notifications@github.com>Date: Sat,Aug 3,2019 4:57 PMTo: huangyh09/briekit <briekit@noreply.github.com>Cc: Ivymanman <ncuskxiaolixing@163.com>, Author <author@noreply.github.com>Subject: Re: [huangyh09/briekit] briekit-event-filter (#1)Hi, the briekit-event-filter is only for the skipping exon events. You may need to define your own filters for the A3SS (alternative 3' splice site) event, which we haven't looked into.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/huangyh09/briekit/issues/1?email_source=notifications\u0026email_token=AL6XVIFE2OEZVMLH7FUU2ZDQCVCBDA5CNFSM4IJCMSQKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD3PKLNI#issuecomment-517907893",
"url": "https://github.com/huangyh09/briekit/issues/1?email_source=notifications\u0026email_token=AL6XVIFE2OEZVMLH7FUU2ZDQCVCBDA5CNFSM4IJCMSQKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD3PKLNI#issuecomment-517907893",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by jihongma1010** [comment]
hi, I got this error when I run
 briekit-event -a /disk1/reference_genome/hg38_ucsc_ercc/Gencodev32_hg38_ercc_refseq.gtf -o /disk2/brie_rnasplicing_bc25/bc25_as/
Making GFF alternative events annotation...
  - Input annotation files: /disk1/reference_genome/hg38_ucsc_ercc/Gencodev32_hg38_ercc_refseq.gtf
  - Output dir: /disk2/brie_rnasplicing_bc25/bc25_as/
('Reading table', '/disk1/reference_genome/hg38_ucsc_ercc/Gencodev32_hg38_ercc_refseq.gtf')
Traceback (most recent call last):
  File "/home/JHma/miniconda3/envs/RNASEQ/bin/briekit-event", line 11, in <module>
    load_entry_point('briekit==0.2.2', 'console_scripts', 'briekit-event')()
  File "build/bdist.linux-x86_64/egg/briekit/events/event_maker.py", line 175, in main
  File "build/bdist.linux-x86_64/egg/briekit/events/event_maker.py", line 69, in defineAllSplicing
  File "build/bdist.linux-x86_64/egg/briekit/events/event_maker.py", line 39, in prepareSplicegraph
  File "build/bdist.linux-x86_64/egg/briekit/events/parseTables.py", line 85, in populateSplicegraph
  File "build/bdist.linux-x86_64/egg/briekit/events/parseTables.py", line 64, in readTable_gff
UnboundLocalError: local variable 'exons' referenced before assignment

Could you help me? Thanks
