### ISSUE TITLE
About using brisket on other species

### ISSUE THREAD

**Issue by hfl112** [huangyh09/briekit#4]
Got a problem using briekit on rheMac10, for rheMac didn't have corresponding phastcon files. And it's too time-consuming to generate a new one. So can I just skip the final step "Extacting sequence feature for BRIE" to do brie-count or brie-quant?
Any advices might help. Thank you

**Comment by huangyh09** [comment]
It is reasonable to not include the conservation score. You can simply not porviding the `--phastCons` option.

Actually, for `brie-quant` from >v2.0, you can entirely ignore gene-level features, and use the cell-level aggregation for imputation or testing your candidate cell-level covariate for differential splicing events.

Yuanhua

**Comment by hfl112** [comment]
> It is reasonable to not include the conservation score. You can simply not porviding the `--phastCons` option.
> 
> Actually, for `brie-quant` from >v2.0, you can entirely ignore gene-level features, and use the cell-level aggregation for imputation or testing your candidate cell-level covariate for differential splicing events.
> 
> Yuanhua

Thanks!
